# Generated by Django 4.2.24 on 2025-12-07 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam/Tin rác'), ('INAPPROPRIATE', 'Nội dung không phù hợp'), ('HATE_SPEECH', 'Ngôn từ thù ghét'), ('VIOLENCE', 'Bạo lực'), ('OTHER', 'Lý do khác')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('RESOLVED', 'Đã xử lý (Xóa bài)'), ('IGNORED', 'Bỏ qua (Không vi phạm)')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
