# Generated by Django 4.1.13 on 2025-11-15 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.ImageField(default='group_default.png', upload_to='group_avatars/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Cá nhân'), ('GROUP', 'Nhóm')], default='PRIVATE', max_length=10),
        ),
    ]
