# Generated by Django 4.1.13 on 2025-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_admin_conversation_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admin_only_management',
            field=models.BooleanField(default=True),
        ),
    ]
