# Generated by Django 4.2.24 on 2025-11-27 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_conversation_admin_conversation_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='type',
        ),
        migrations.AddField(
            model_name='message',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
