# Generated by Django 4.1.13 on 2025-11-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_groupmembershiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
    ]
