# Generated by Django 4.2.24 on 2025-12-01 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
