# Generated by Django 4.2.24 on 2025-11-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FRIEND_REQUEST', 'Yêu cầu kết bạn'), ('POST_LIKE', 'Thích bài viết'), ('POST_COMMENT', 'Bình luận bài viết'), ('COMMENT_REACTION', 'Bày tỏ cảm xúc về bình luận'), ('MESSAGE', 'Tin nhắn mới')], max_length=20),
        ),
    ]
