# Generated by Django 4.1.13 on 2025-11-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FRIEND_REQUEST', 'Yêu cầu kết bạn'), ('POST_LIKE', 'Thích bài viết'), ('POST_COMMENT', 'Bình luận bài viết'), ('COMMENT_REACTION', 'Bày tỏ cảm xúc về bình luận'), ('MESSAGE', 'Tin nhắn mới'), ('ADDED_TO_GROUP', 'Được thêm vào nhóm')], max_length=20),
        ),
    ]
