# Generated by Django 4.2.24 on 2025-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FRIEND_REQUEST', 'Yêu cầu kết bạn'), ('FRIEND_ACCEPT', 'Chấp nhận lời mời kết bạn'), ('POST_LIKE', 'Thích bài viết'), ('POST_COMMENT', 'Bình luận bài viết'), ('COMMENT_REACTION', 'Bày tỏ cảm xúc về bình luận'), ('MESSAGE', 'Tin nhắn mới'), ('MESSAGE_REACTION', 'Bày tỏ cảm xúc về tin nhắn'), ('ADDED_TO_GROUP', 'Được thêm vào nhóm'), ('GROUP_INVITE_REQUEST', 'Yêu cầu phê duyệt thành viên')], max_length=50),
        ),
    ]
